### ISSUE TITLE
Devices become unavailable after time-out

### ISSUE THREAD

**Issue by botmanshassio** [Arbuzov/hass-broadlink-ac-mqtt#10]
whenever a command cannot be sent due to a time-out, all of the devices become unavailable and I need to restart the service for them to become available again.
1 of my airco's keeps giving random time-outs, funny enough it's the one closest to my router.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun broadlink-ac-mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting Monitor...
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
(200, ('192.168.1.98', 80))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/share/broadlink_ac_mqtt-1.2.1b/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 252, in send_packet
    response = self.cs.recvfrom(1024)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/share/broadlink_ac_mqtt-1.2.1b/broadlink_ac_mqtt/AcToMqtt.py", line 408, in _on_mqtt_message
    status = self.device_objects[address].set_fanspeed(value)
  File "/usr/share/broadlink_ac_mqtt-1.2.1b/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 439, in set_fanspeed
    self.get_ac_states()
  File "/usr/share/broadlink_ac_mqtt-1.2.1b/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 710, in get_ac_states
    response = self.send_packet(0x6a, GET_STATES)	
  File "/usr/share/broadlink_ac_mqtt-1.2.1b/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 258, in send_packet
    raise ConnectTimeout(200,self.host)
broadlink_ac_mqtt.classes.broadlink.ac_db.ConnectTimeout: (200, ('192.168.1.98', 80))

**Comment by ArtemVladimirov** [comment]
The author of the script advised such a solution
https://github.com/liaan/broadlink_ac_mqtt/issues/110

**Comment by Arbuzov** [comment]
The specific behaviour you describe — one flaky unit's time-out taking every device down until a restart — has been addressed:

- A command that raised while being handled used to end the MQTT client's network thread. The add-on stayed running but stopped reacting to everything, for every device, until restarted. Fixed in 0.6.10: the exception is logged and the loop continues.
- The 1-second socket time-out in the device driver had a retry that never actually retried. Fixed upstream.
- A unit that stops answering is now skipped and re-created on a later poll instead of staying dead until a restart (0.6.9 / 0.7.0).

So a time-out on the AC nearest your router should now cost you that one device for a poll or two, not the whole set. Please give 0.7.1 a try (published shortly) and reopen the conversation here if a single unit's time-out still takes the others with it.
